### ISSUE TITLE
[新功能] momotalk merge (amend)

### ISSUE THREAD

**Issue by Mark9804** [ba-archive/ba-razor#1]
目前 momotalk merge 的机制是用国际服的文件直接覆盖掉日服的文件。

这个机制存在一个弊端，例如，假如日服某个角色（比如 16001 明日奈）开了爱用品剧情，但是国际服还没有开，那么日服的爱用品剧情就直接丢失了。

所以更好的方式是将 jp 分支的文件和 global 分支的文件输出到两个分别的文件夹，再通过查找信息 ID 的方式将国际服已有的翻译 merge 到 jp 分支文件当中。

这个流程在之后将国际服更新后的翻译文件重新复用到我们已有的日服翻译文件里面（例如，20020 日鞠目前只有日服的翻译，国际服出了日鞠之后，我们也可以用相同的流程把国际服翻译更新到已有的日服文件里来）

详细流程图见下。

<details>
<summary>流程图</summary>

![workflow](https://user-images.githubusercontent.com/9006264/207871880-c72521cf-bcf4-483b-b98c-d5de8f5f938f.png)
</details>

**Comment by notnotype** [comment]
2a3edab4220bc292dc63f18aa18280f2251747e7
